name: Terraform CI/CD - All Environments

on:
  push:
    branches:
      - main

jobs:
  dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_vm_username: ${{ secrets.TF_VAR_vm_username }}
      TF_VAR_vm_password: ${{ secrets.TF_VAR_vm_password }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Init (Dev)
        run: terraform init -backend-config="key=3tier/dev.terraform.tfstate"
      - name: Plan (Dev)
        run: terraform plan -var-file="environments/dev/terraform.tfvars"

      - name: Apply (Dev)
        run: terraform apply -auto-approve -var-file="environments/dev/terraform.tfvars"
  test:
    name: Deploy Test
    runs-on: ubuntu-latest
    environment: test
    needs: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_vm_username: ${{ secrets.TF_VAR_vm_username }}
      TF_VAR_vm_password: ${{ secrets.TF_VAR_vm_password }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Init (Test)
        run: terraform init -backend-config="key=3tier/test.terraform.tfstate"

      - name: Plan (Test)
        run: terraform plan -var-file="environments/test/terraform.tfvars"
      - name: Apply (Test)
        run: terraform apply -auto-approve -var-file="environments/test/terraform.tfvars"
  prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    environment: prod
    needs: [dev, test]
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_vm_username: ${{ secrets.TF_VAR_vm_username }}
      TF_VAR_vm_password: ${{ secrets.TF_VAR_vm_password }}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      - name: Init (Prod)
        run: terraform init -backend-config="key=3tier/prod.terraform.tfstate"

      - name: Plan (Prod)
        run: terraform plan -var-file="environments/prod/terraform.tfvars"
      - name: Apply (Prod)
        run: terraform apply -auto-approve -var-file="environments/prod/terraform.tfvars"